substitutions:
devicename: cesp1generic
friendly_name: cesp1 smart plug generic

esphome:
name: ${devicename}
friendly_name: ${friendly_name}

rtl87xx:
  board: generic-rtl8710bx-4mb-980k

# Enable logging
logger:
# Enable Home Assistant API
api:
  encryption:
    key: "CHANGE_ME"

ota:
  - platform: esphome
  - password: "CHANGE_ME"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.0.x.x
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ce-Sp1-Generic Fallback Hotspot"
    password: "CHANGE_ME"
  captive_portal:

web_server:
  port: 80

status_led:
  pin:
    number: PA5
    inverted: true

text_sensor:
  - platform: libretiny
    version:
      name: LibreTiny Version

sensor:
  - platform: uptime
    name: Uptime
    filters:
      - lambda: return x / 60.0;
    unit_of_measurement: minutes

  - platform: wifi_signal
    name: Wifi Signal
    update_interval: 60s

binary_sensor:
  - platform: gpio
    device_class: power
    name: ${devicename} button
    pin:
      number: PA22
      mode: INPUT_PULLUP
      inverted: true
      on_press:
        - switch.toggle: relay 

switch:
  - platform: gpio
  - id: relay
  - name: ${devicename} relay
  - pin: PA00
  - restore_mode: RESTORE_DEFAULT_OFF
